import { OverseasEtfCandidate } from '@/types/etf';

export const CURATED_OVERSEAS_ETFS: OverseasEtfCandidate[] = [
  { ticker: "SPY", name: "SPDR S&P 500 ETF Trust" },
  { ticker: "VOO", name: "Vanguard S&P 500 ETF" },
  { ticker: "VTI", name: "Vanguard Total Stock Market ETF" },
  { ticker: "QQQ", name: "Invesco QQQ Trust" },
  { ticker: "IVV", name: "iShares Core S&P 500 ETF" },
  { ticker: "DIA", name: "SPDR Dow Jones Industrial Average ETF" },
  { ticker: "IWM", name: "iShares Russell 2000 ETF" },
  { ticker: "EFA", name: "iShares MSCI EAFE ETF" },
  { ticker: "VEA", name: "Vanguard FTSE Developed Markets ETF" },
  { ticker: "VWO", name: "Vanguard FTSE Emerging Markets ETF" },
  { ticker: "GLD", name: "SPDR Gold Shares" },
  { ticker: "SLV", name: "iShares Silver Trust" },
  { ticker: "TLT", name: "iShares 20+ Year Treasury Bond ETF" },
  { ticker: "IEF", name: "iShares 7-10 Year Treasury Bond ETF" },
  { ticker: "AGG", name: "iShares Core U.S. Aggregate Bond ETF" },
  { ticker: "BND", name: "Vanguard Total Bond Market ETF" },
  { ticker: "XLK", name: "Technology Select Sector SPDR Fund" },
  { ticker: "XLF", name: "Financial Select Sector SPDR Fund" },
  { ticker: "XLE", name: "Energy Select Sector SPDR Fund" },
  { ticker: "XLV", name: "Health Care Select Sector SPDR Fund" },
  { ticker: "SMH", name: "VanEck Semiconductor ETF" },
  { ticker: "SOXX", name: "iShares Semiconductor ETF" },
  { ticker: "ARKK", name: "ARK Innovation ETF" },
  { ticker: "SCHD", name: "Schwab US Dividend Equity ETF" },
  { ticker: "VYM", name: "Vanguard High Dividend Yield ETF" },
  { ticker: "JEPI", name: "JPMorgan Equity Premium Income ETF" },
  { ticker: "VNQ", name: "Vanguard Real Estate ETF" },
  { ticker: "USO", name: "United States Oil Fund" },
  { ticker: "EEM", name: "iShares MSCI Emerging Markets ETF" },
  { ticker: "HYG", name: "iShares iBoxx High Yield Corp Bond ETF" },
];